[phases.build]
cmds = [
  "npm install --no-cache --prefer-offline",
  "npm run db:push",
  "npm run build"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"

[providers.node]
version = "18"