[phases.build]
cmds = [
  "npm install --no-cache --prefer-offline --omit=dev",
  "npm install --no-cache --prefer-offline --include=dev",
  "npm run build"
]

[phases.start]
cmd = "node start.js"

[variables]
NODE_ENV = "production"